// Code generated by protoc-gen-go. DO NOT EDIT.
// source: challenge_message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Challenge struct {
	Title                string           `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string           `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Description          string           `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags                 string           `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	Requirements         string           `protobuf:"bytes,5,opt,name=requirements,proto3" json:"requirements,omitempty"`
	File                 []*ChallengeFile `protobuf:"bytes,6,rep,name=file,proto3" json:"file,omitempty"`
	Level                string           `protobuf:"bytes,7,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Challenge) Reset()         { *m = Challenge{} }
func (m *Challenge) String() string { return proto.CompactTextString(m) }
func (*Challenge) ProtoMessage()    {}
func (*Challenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e18aabac6b3a996, []int{0}
}

func (m *Challenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Challenge.Unmarshal(m, b)
}
func (m *Challenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Challenge.Marshal(b, m, deterministic)
}
func (m *Challenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Challenge.Merge(m, src)
}
func (m *Challenge) XXX_Size() int {
	return xxx_messageInfo_Challenge.Size(m)
}
func (m *Challenge) XXX_DiscardUnknown() {
	xxx_messageInfo_Challenge.DiscardUnknown(m)
}

var xxx_messageInfo_Challenge proto.InternalMessageInfo

func (m *Challenge) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Challenge) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Challenge) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Challenge) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Challenge) GetRequirements() string {
	if m != nil {
		return m.Requirements
	}
	return ""
}

func (m *Challenge) GetFile() []*ChallengeFile {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Challenge) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

type ChallengeFile struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChallengeFile) Reset()         { *m = ChallengeFile{} }
func (m *ChallengeFile) String() string { return proto.CompactTextString(m) }
func (*ChallengeFile) ProtoMessage()    {}
func (*ChallengeFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e18aabac6b3a996, []int{1}
}

func (m *ChallengeFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChallengeFile.Unmarshal(m, b)
}
func (m *ChallengeFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChallengeFile.Marshal(b, m, deterministic)
}
func (m *ChallengeFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChallengeFile.Merge(m, src)
}
func (m *ChallengeFile) XXX_Size() int {
	return xxx_messageInfo_ChallengeFile.Size(m)
}
func (m *ChallengeFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ChallengeFile.DiscardUnknown(m)
}

var xxx_messageInfo_ChallengeFile proto.InternalMessageInfo

func (m *ChallengeFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChallengeFile) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type NewChallengeRequest struct {
	Challenge            *Challenge `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NewChallengeRequest) Reset()         { *m = NewChallengeRequest{} }
func (m *NewChallengeRequest) String() string { return proto.CompactTextString(m) }
func (*NewChallengeRequest) ProtoMessage()    {}
func (*NewChallengeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e18aabac6b3a996, []int{2}
}

func (m *NewChallengeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewChallengeRequest.Unmarshal(m, b)
}
func (m *NewChallengeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewChallengeRequest.Marshal(b, m, deterministic)
}
func (m *NewChallengeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewChallengeRequest.Merge(m, src)
}
func (m *NewChallengeRequest) XXX_Size() int {
	return xxx_messageInfo_NewChallengeRequest.Size(m)
}
func (m *NewChallengeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewChallengeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewChallengeRequest proto.InternalMessageInfo

func (m *NewChallengeRequest) GetChallenge() *Challenge {
	if m != nil {
		return m.Challenge
	}
	return nil
}

type NewChallengeResponse struct {
	ChallengeId          string   `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewChallengeResponse) Reset()         { *m = NewChallengeResponse{} }
func (m *NewChallengeResponse) String() string { return proto.CompactTextString(m) }
func (*NewChallengeResponse) ProtoMessage()    {}
func (*NewChallengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e18aabac6b3a996, []int{3}
}

func (m *NewChallengeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewChallengeResponse.Unmarshal(m, b)
}
func (m *NewChallengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewChallengeResponse.Marshal(b, m, deterministic)
}
func (m *NewChallengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewChallengeResponse.Merge(m, src)
}
func (m *NewChallengeResponse) XXX_Size() int {
	return xxx_messageInfo_NewChallengeResponse.Size(m)
}
func (m *NewChallengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewChallengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewChallengeResponse proto.InternalMessageInfo

func (m *NewChallengeResponse) GetChallengeId() string {
	if m != nil {
		return m.ChallengeId
	}
	return ""
}

func init() {
	proto.RegisterType((*Challenge)(nil), "gogrpc.code.acampagnaro.Challenge")
	proto.RegisterType((*ChallengeFile)(nil), "gogrpc.code.acampagnaro.ChallengeFile")
	proto.RegisterType((*NewChallengeRequest)(nil), "gogrpc.code.acampagnaro.NewChallengeRequest")
	proto.RegisterType((*NewChallengeResponse)(nil), "gogrpc.code.acampagnaro.NewChallengeResponse")
}

func init() {
	proto.RegisterFile("challenge_message.proto", fileDescriptor_9e18aabac6b3a996)
}

var fileDescriptor_9e18aabac6b3a996 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0x31, 0x4f, 0xeb, 0x30,
	0x10, 0xc7, 0x5f, 0xda, 0xb4, 0x4f, 0xbd, 0xf4, 0xe9, 0x55, 0xa6, 0x52, 0x23, 0xa6, 0xe2, 0x01,
	0x75, 0x80, 0x0c, 0x45, 0x0c, 0x30, 0x21, 0x2a, 0x21, 0xb1, 0x30, 0x84, 0x01, 0x89, 0x05, 0xb9,
	0xc9, 0x61, 0x2c, 0x39, 0xb1, 0xb1, 0xdd, 0xf2, 0x05, 0xf8, 0xa2, 0x7c, 0x13, 0x1a, 0xa7, 0x4d,
	0xa9, 0x44, 0x05, 0xdb, 0xdf, 0xff, 0xbb, 0x7f, 0xf4, 0xbb, 0xbb, 0xc0, 0x28, 0x7b, 0x61, 0x52,
	0x62, 0xc9, 0xf1, 0xa9, 0x40, 0x6b, 0x19, 0xc7, 0x44, 0x1b, 0xe5, 0x14, 0x19, 0x71, 0xc5, 0x8d,
	0xce, 0x92, 0x4c, 0xe5, 0x98, 0xb0, 0x8c, 0x15, 0x9a, 0xf1, 0x92, 0x19, 0x45, 0x3f, 0x02, 0xe8,
	0xcd, 0x36, 0x21, 0x32, 0x84, 0x8e, 0x13, 0x4e, 0x62, 0x1c, 0x8c, 0x83, 0x49, 0x2f, 0xad, 0x1f,
	0x84, 0x40, 0x68, 0xe5, 0x82, 0xc7, 0x2d, 0x6f, 0x7a, 0x4d, 0xc6, 0x10, 0xe5, 0x68, 0x33, 0x23,
	0xb4, 0x13, 0xaa, 0x8c, 0xdb, 0xbe, 0xf4, 0xd5, 0xaa, 0x52, 0x8e, 0x71, 0x1b, 0x87, 0x75, 0xaa,
	0xd2, 0x84, 0x42, 0xdf, 0xe0, 0xeb, 0x42, 0x18, 0x2c, 0xb0, 0x74, 0x36, 0xee, 0xf8, 0xda, 0x8e,
	0x47, 0x2e, 0x21, 0x7c, 0x16, 0x2b, 0x84, 0xee, 0xb8, 0x3d, 0x89, 0xa6, 0xc7, 0xc9, 0x1e, 0xf2,
	0xa4, 0xa1, 0xbe, 0x59, 0x75, 0xa7, 0x3e, 0x53, 0xf1, 0x4b, 0x5c, 0xa2, 0x8c, 0xff, 0xd6, 0xfc,
	0xfe, 0x41, 0xcf, 0xe1, 0xdf, 0x4e, 0x73, 0x85, 0x56, 0xb2, 0x02, 0x37, 0x03, 0x55, 0x9a, 0x0c,
	0xa0, 0xbd, 0x30, 0x72, 0x3d, 0x48, 0x25, 0xe9, 0x03, 0x1c, 0xdc, 0xe1, 0x5b, 0x93, 0x4c, 0x57,
	0x90, 0x68, 0x1d, 0xb9, 0x82, 0x5e, 0xb3, 0x65, 0xbf, 0xa7, 0x68, 0x4a, 0x7f, 0x86, 0x4c, 0xb7,
	0x21, 0x7a, 0x01, 0xc3, 0xdd, 0x0f, 0x5b, 0xad, 0x4a, 0x8b, 0xe4, 0x08, 0xfa, 0xdb, 0xfb, 0x89,
	0x7c, 0x7d, 0x84, 0xa8, 0xf1, 0x6e, 0xf3, 0xe9, 0x7b, 0x00, 0x83, 0x26, 0x78, 0x8f, 0x66, 0x29,
	0x32, 0x24, 0x1a, 0xfe, 0xcf, 0x0c, 0x32, 0x87, 0xdb, 0x43, 0x9e, 0xec, 0x25, 0xfa, 0x66, 0xa4,
	0xc3, 0xd3, 0x5f, 0x76, 0xd7, 0x9c, 0xf4, 0xcf, 0x75, 0xf8, 0xd8, 0xd2, 0xf3, 0x79, 0xd7, 0xff,
	0x5b, 0x67, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x5e, 0xfe, 0xb5, 0x76, 0x02, 0x00, 0x00,
}
