// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7965fb6944d08275, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7965fb6944d08275, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserAuthRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAuthRequest) Reset()         { *m = UserAuthRequest{} }
func (m *UserAuthRequest) String() string { return proto.CompactTextString(m) }
func (*UserAuthRequest) ProtoMessage()    {}
func (*UserAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7965fb6944d08275, []int{2}
}

func (m *UserAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuthRequest.Unmarshal(m, b)
}
func (m *UserAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuthRequest.Marshal(b, m, deterministic)
}
func (m *UserAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuthRequest.Merge(m, src)
}
func (m *UserAuthRequest) XXX_Size() int {
	return xxx_messageInfo_UserAuthRequest.Size(m)
}
func (m *UserAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuthRequest proto.InternalMessageInfo

func (m *UserAuthRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserAuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "gogrpc.code.acampagnaro.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "gogrpc.code.acampagnaro.UserResponse")
	proto.RegisterType((*UserAuthRequest)(nil), "gogrpc.code.acampagnaro.UserAuthRequest")
}

func init() {
	proto.RegisterFile("user_message.proto", fileDescriptor_7965fb6944d08275)
}

var fileDescriptor_7965fb6944d08275 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x49, 0x08, 0x08, 0x06, 0x24, 0xa4, 0x11, 0x12, 0x51, 0x57, 0x28, 0x2a, 0x52, 0x57,
	0x5e, 0xc0, 0x09, 0xa0, 0x37, 0x68, 0xc5, 0x02, 0x58, 0xa0, 0x69, 0x3a, 0x0a, 0x15, 0xc4, 0x63,
	0x3c, 0x0e, 0x9c, 0x90, 0x7b, 0x41, 0x6c, 0xa8, 0xca, 0x22, 0xd0, 0x9d, 0xff, 0xf8, 0xfb, 0x7f,
	0x3f, 0x0d, 0x60, 0xa7, 0xec, 0x1f, 0x5b, 0x56, 0xa5, 0x86, 0x8d, 0xf3, 0x12, 0x04, 0xcf, 0x1a,
	0x69, 0xbc, 0xab, 0x4d, 0x2d, 0x4b, 0x36, 0x54, 0x53, 0xeb, 0xa8, 0xb1, 0xe4, 0xa5, 0x9a, 0xc3,
	0xd1, 0xed, 0x97, 0x7d, 0xc6, 0xaf, 0x1d, 0x6b, 0x40, 0x84, 0xc2, 0x52, 0xcb, 0x65, 0x76, 0x9e,
	0x4d, 0x0e, 0x67, 0xf1, 0x8c, 0xa7, 0xb0, 0xc7, 0x2d, 0xad, 0x5e, 0xca, 0x3c, 0x0e, 0x93, 0xc0,
	0x11, 0x1c, 0x38, 0x52, 0x7d, 0x17, 0xbf, 0x2c, 0x77, 0xe3, 0xc5, 0x5a, 0x57, 0x63, 0x38, 0x4e,
	0xa1, 0xea, 0xc4, 0x6a, 0x4c, 0x08, 0xf2, 0xcc, 0xf6, 0x3b, 0x36, 0x89, 0x6a, 0x0a, 0x27, 0xbd,
	0xeb, 0xba, 0x0b, 0x4f, 0x3f, 0xf5, 0xeb, 0xaa, 0x6c, 0xa8, 0x2a, 0xff, 0x5d, 0x75, 0xf9, 0x91,
	0x25, 0x80, 0x39, 0xfb, 0xb7, 0x55, 0xcd, 0xf8, 0x00, 0x30, 0xf5, 0x4c, 0x81, 0xfb, 0x21, 0x8e,
	0xcd, 0x00, 0xb7, 0xd9, 0x80, 0x1e, 0x5d, 0xfc, 0xe3, 0x4a, 0x14, 0xd5, 0x0e, 0xde, 0x41, 0xd1,
	0xff, 0x16, 0x27, 0x7f, 0x3e, 0xd8, 0x00, 0xda, 0x3a, 0xfa, 0xa6, 0xb8, 0xcf, 0xdd, 0x62, 0xb1,
	0x1f, 0xb7, 0x75, 0xf5, 0x19, 0x00, 0x00, 0xff, 0xff, 0x68, 0x0c, 0xa0, 0x9c, 0xc3, 0x01, 0x00,
	0x00,
}
